baseURL = "https://altmanea.ru/it/"
languageCode = "ru"
title = "Информационные технологии"
theme = "hugo-theme-techdoc"

[params]
    custom_font_color = "white"
    custom_background_color = "blue"

    lecUrl = "https://altmanea.ru/it/slides/"

    menu_style = "open-menu"
    menu_exclusion = ["home", "archives", "blog", "entry", "post", "posts"]

