baseURL = "https://altmanea.ru/oop/"
languageCode = "ru"
title = "Объектно-ориентированное программирование"
theme = "hugo-theme-techdoc"

[params]
    custom_font_color = "white"
    custom_background_color = "blue"

    lecUrl = "https://altmanea.ru/oop/slides/"

    menu_style = "open-menu"
    menu_exclusion = ["home", "archives", "blog", "entry", "post", "posts"]

[markup]
  [markup.highlight]
    style = "github"
