baseURL = "https://altmanea.ru/rest/"
languageCode = "ru"
title = "Разработка REST-сервера"
theme = "hugo-theme-techdoc"

[params]
    custom_font_color = "white"
    custom_background_color = "blue"

    lecUrl = "https://altmanea.ru/rest/slides/"

    menu_style = "open-menu"
    menu_exclusion = ["home", "archives", "blog", "entry", "post", "posts"]

